### PR TITLE
Feature/#75 sponsor functionality

### LINKED ISSUE #75: task - endpoint patrocinio
## related
- child of #55 

## description 
endpoint que incluya la gestión de anuncios, ofertas de patrocinio y la relación entre sponsor y evento (sponsorship)

## to-do
- [ ] crear oferta de patrocinio (anuncio, suma de dinero, estado aceptada/rechazada ..)
- [ ] relación intermedia entre sponsor y evento (oferta de patrocinio)
- [ ] consulta de ofertas para un evento y para un usuario (eventos de ese usuario)
- [ ] acción de aceptación/rechazo de oferta (U)

## accept
- [ ] endpoint para la gestión de patrocinios usable y documentado

### PR DESCRIPTION
**Pull request by pabgonmon2**
close #75 #99 

  ## changes
  - Created new class Sponsorship
  - Created new Endpoint Sponshorship with CRUD operations

  ## steps to review
  - Review code implementation
  - Test endpoints with postman
  
  
  ## concerns
  - Tests need to be implemented
  - Media class not added in Sponshorship attributes

### CODE REVIEW

**Review by josrompoz1 — CHANGES_REQUESTED** [review]
Falta la funcionalidad aceptar/rechazar patrocinios

**Comment by pabgonmon2** [comment]
Added resolve sponsorship functionality.
Now, there's an endpoint where a user can accept or deny their sponsorship.
There's also an endpoint to list the sponsorships denied or accepted for any event.

**Review by pedalopon — APPROVED** [review]
## Review
- Review general code implementation and its all okey
- Tested all endpoints of the new sponsorController

**Review by josrompoz1 — APPROVED** [review]
Tested endpoints with postman.

**Pull request merged**
